[mongodb]
mongodb-dev.daws880s.online

[catalogue]
catalogue-dev.daws880s.online
[redis]
redis-dev.daws880s.online

[all:vars]

ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.daws880s.online