[mongodb]
mongodb-dev.daws880s.online

[catalogue]
catalogue-dev.daws880s.online
[redis]
redis-dev.daws880s.online

[user]
user-dev.daws880s.online

[cart]
cart-dev.daws880s.online

[mysql]
mysql-dev.daws880s.online

[all:vars]

ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.daws880s.online
CATALOGUE_HOST=catalogue-dev.daws880s.online
REDIS_HOST=redis-dev.daws880s.online
CART_HOST=cart-dev.daws880s.online