- name: mongodb configuration
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongorepo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: installed the mongodb-org
    ansible.builtin.dnf:
      name: mongodb-org 
      state: present

  - name: start and enable the mongod
    ansible.builtin.service: 
      name: mongod
      state: started
      enabled: yes

  - name: allowing the remote access
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'  

  - name: Restart the MongoDB service
    ansible.builtin.service:
      name: mongod
      state: restarted    