- name: user configuration
  hosts: user
  become: yes
  tasks: 
  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: user
      state: present

  - name:  creating the roboshop user
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /bin/bash 
      comment: "roboshop system user"

  - name: deleting the app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creating the app directory
    ansible.builtin.file:
      path: /tmp/user.zip
      state: directory

  - name: delete user zip file
    ansible.builtin.file:
      path: /tmp/user.zip
      state: absent

  - name: Download zip file
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip 

  - name: Install packages npm.
    community.general.npm:
      path: /app    
       
  - name: copy the systemctl services
    ansible.builtin.copy:
      src: user.services
      dest: /etc/systemd/system/user.service

  - name: system demonreload
    ansible.builtin.systemd_service:
      daemon_reload: true
      name: user

  - name: enable and start
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes        
